# Description: This file contains the variables that are common to all the hosts in the inventory.

# The user to create on each node for access by ansible
ansible_account: "ansible"
# The user used to connect to the tpi BMCs
tpi_user: root
# A path to some storage on the tpi BMCs used for downloading os images
tpi_images_path: /mnt/sdcard/images

# location of binaries we install in the execution environment
bin_dir: "{{ lookup('ansible.builtin.env', 'BIN_DIR', default='${HOME}/bin') }}"

# tracks the node name of the control plane
control_plane_ip: "{{ hostvars[control_plane]['ansible_default_ipv4']['address'] }}"
# uncomment for a specific version of k3s (see https://github.com/k3s-io/k3s/releases)
# k3s_version:. v1.29.11+k3s1

# control which phases of the ALL playbook are run. Override on the command line
do_tools: true
do_flash: false # Gary has no turing pi
do_k3s: true
do_cluster: true

################################################################################
# EDIT BELOW ###################################################################
# The remaining variables are for personalization of the cluster ###############
################################################################################

admin_password: notgood # change this! (TODO: get keycloak working and ansible vault an initial password)
local_domain: .local # how to address local nodes with mDNS
control_plane: raspberrypi.local # the node name of the control plane
cluster_domain: raspberrypi.local # the DNS name for the cluster control plane node
domain_email: gary@raspberrypi.local # (for lets_encrypt only)

# List of features to install into the cluster, comment out to remove.
# Each entry must match the name of a tasks yaml file in the cluster role.
cluster_install_list:
  - ingress
  # - lets_encrypt
  # - longhorn
  - dashboard
  # - grafana
  - echo
  # - keycloak
  - pihole
