temp_folder: /tmp/iac2-rk1/

image_version: 1.33
image:
  # TODO - don't forget to try out Talos at some point!
  version: 1.33
  url: https://firmware.turingpi.com/turing-rk1/ubuntu_22.04_rockchip_linux/v{{image_version}}/ubuntu-22.04.3-preinstalled-server-arm64-turing-rk1_v1.33.img.xz
  sha: https://firmware.turingpi.com/turing-rk1/ubuntu_22.04_rockchip_linux/v{{image_version}}/ubuntu-22.04.3-preinstalled-server-arm64-turing-rk1_v1.33.img.xz.sha256
  os_file: "{{ temp_folder }}os.{{image_version}}.img.xz"
  sha_file: "{{ temp_folder }}os.{{image_version}}.sha"

auser:
  uid: 1002:1003
  passwd: |-
    ansible:x:1002:1003:ansible User:/home/ansible:/bin/bash
  # TODO remove password hash once ssh key is working
  shadow: |-
    ansible:$1$xyz$jAlmRpcFe.aiPOIXET9GG/:::::::
  group: |-
    ansible:x:1003:
  sudo: |-
    ansible ALL=(ALL) NOPASSWD:ALL
  ssh: |-
    /mnt/node/home/ansible/.ssh/
