- name: Extract the group that lists this turing pi's nodes
  ansible.builtin.set_fact:
    nodes: |-
      {{ groups[hostvars[inventory_hostname].nodes_group] }}

- name: List the nodes for '{{ inventory_hostname }}'
  ansible.builtin.debug:
    var: nodes

- name: Process the nodes for '{{ inventory_hostname }}'
  ansible.builtin.include_tasks: node.yml
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node_name