# Tasks run against a single node in a turingpi

- name: Fetch Node Variables for {{ node_name }}
  ansible.builtin.set_fact:
    node: "{{ hostvars[node_name] }}"

# determine if the node already can accept ssh
- name: Wait for {{ node_name }}
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ node_name }}"
    port: 22
    timeout: 2
  register: node_status
  ignore_errors: true

- name: Flash images
  ansible.builtin.include_tasks: flash.yml
  when: node_status is failed or flash_force

- name: Bootstrap node to enable further ansible provisioning
  ansible.builtin.include_tasks: bootstrap.yml
  # if the node is already contactable then no need to do initial boot cloud init
  when: node_status is failed or flash_force
