# details of the OS images to flast onto the nodes
rk1_image_version: "1.33"
rp4_image_version: "24.04.1"
image_info:
  # TODO - don't forget to try out Talos at some point!
  rk1:
    url: https://firmware.turingpi.com/turing-rk1/ubuntu_22.04_rockchip_linux/v{{rk1_image_version}}/ubuntu-22.04.3-preinstalled-server-arm64-turing-rk1_v1.33.img.xz
    sha: fa345ea9184be5b097f72c5ca451da197991b69d2e6affcb0d3ebaf124708226
    os_file: "{{ local_tmp }}/os.{{rk1_image_version}}.img.xz"
    osf_remote: "{{ tpi_images_path }}/os.{{rk1_image_version}}.img.xz"
  pi4:
    url: https://cdimage.ubuntu.com/releases/{{ rp4_image_version }}/release/ubuntu-{{ rp4_image_version }}-preinstalled-server-arm64+raspi.img.xz
    sha: e59925e211080b20f02e4504bb2c8336b122d0738668491986ee29a95610e5b1
    os_file: "{{ local_tmp }}/os.raspi{{ rp4_image_version }}.img.xz"
    osf_remote: "{{ tpi_images_path }}/os.raspi{{ rp4_image_version }}.img.xz"

local_tmp: /tmp/iac2
