- name: Get helm version 3.16.4 amd binary
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.16.4-linux-amd64.tar.gz
    dest: /tmp/helm-v3.6.3-linux-amd64.tar.gz
    mode: "0644"
    checksum: "sha256:fc307327959aa38ed8f9f7e66d45492bb022a66c3e5da6063958254b9767d179"
    validate_certs: true

- name: Extract helm binary
  ansible.builtin.unarchive:
    src: /tmp/helm-v3.6.3-linux-amd64.tar.gz
    dest: /tmp
    remote_src: true
    mode: "0755"
    creates: /tmp/linux-amd64/helm

# the bin folder persists through container rebuilds because it is a volume
- name: Move helm binary to the path
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: "{{ bin_dir }}/helm"
    mode: "0755"
  become: true

# this step is lost on rebuild of the container, so is the only step
# that causes a change after container rebuild
- name: Make kubectl available to all
  ansible.builtin.file:
    src: "{{ bin_dir }}/helm"
    path: /usr/local/bin/helm
    state: link
  become: true

- name: Install helm plugins
  ansible.builtin.command:
    cmd: helm plugin install https://github.com/databus23/helm-diff
    creates: ${HOME}/.local/share/helm/plugins/helm-diff

- name: Command line completion for helm
  ansible.builtin.shell:
    cmd: helm completion {{ item.name }} > {{ item.completion_dir }}/_helm
    creates: "{{ item.completion_dir }}/_helm"
  loop: "{{ tools_shell }}"
