# install tools into the execution environment

- name: Execute the tool task files
  ansible.builtin.include_tasks: |-
    {{ task_file }}.yml
  loop:
    - shell
    - additional
    - helm
    - kubectl
  loop_control:
    loop_var: task_file
