# install tools into the execution environment

- name: Ensure the bin folder exists
  ansible.builtin.file:
    state: directory
    dest: "{{ bin_dir }}"
    mode: "0755"

- name: Add bin folder to path
  ansible.builtin.lineinfile:
    path: "{{ zshrc }}"
    line: 'export PATH="{{ bin_dir }}:$PATH"'
    mode: "0644"
    create: true

- name: Execute helm tasks
  ansible.builtin.include_tasks: helm.yml

- name: Execute kubectl tasks
  ansible.builtin.include_tasks: kubectl.yml
