# add a node with already installed OS to ansible control
- name: Create ansible user (with no password login)
  ansible.builtin.user:
    name: "ansible"
    shell: /bin/bash
    createhome: true
    state: present
  become: true

- name: Create ssh directory for ansible user
  ansible.builtin.file:
    dest: "/home/ansible/.ssh"
    state: directory
    owner: "ansible"
    mode: "0700"
  become: true

- name: Add keys to ansible users authorized_keys
  ansible.builtin.copy:
    src: "pub_keys/ansible_rsa.pub"
    dest: "/home/ansible/.ssh/authorized_keys"
    owner: "ansible"
    mode: "0600"
  become: true

- name: Add ansible user to passwordless sudoers
  ansible.builtin.copy:
    content: "ansible ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/ansible"
    owner: "root"
    group: "root"
    mode: "0440"
  become: true
