- name: Debug
  ansible.builtin.debug:
    var: ansible_facts
  when: do_debug

- name: Create Temporary Directory
  ansible.builtin.file:
    path: "{{ flash_local_tmp }}"
    state: directory
    mode: '0755'
