# Flash an image onto one of the turingpi nodes
#
# commands are delegated to localhost or use 'raw'
# because BMC has no python or disk space
# if the node is already contactable we can skip the remaining steps

- name: select the image to flash for rk1
  set_fact:
    image: "{{ image_info.rk1 }}"
  when: node.type == 'rk1'

- name: select the image to flash for rpi4 compute module
  set_fact:
    image: "{{ image_info.rp4 }}"
  when: node.type == 'pi4'

- name: get OS image for {{ node.type }}
  delegate_to: localhost
  get_url:
    url: "{{ image.url }}"
    dest: "{{ image.os_file }}"
  register: os_file

# this guarentees the state of the node and flash will automatically turn in on
- name: turn off node before flashing
  raw: tpi power off -n {{ node.slot_num }}

- name: flash-image
  delegate_to: localhost
  command:
    cmd: |-
      tpi flash -n {{ node.slot_num }} --host {{ inventory_hostname }}
      --user {{ tpi_user }} --password {{ tpi_password }}
      --image-path {{ os_file.dest }}
      --sha256 {{ image.sha }}
  register: flash_results

- name: show flash results
  debug:
    var: flash_results.stdout_lines

- name: show flash error
  debug:
    var: flash_results.stderr
