- name: extract the group that lists this turing pi's nodes
  set_fact:
    nodes: |-
      {{ groups[hostvars[inventory_hostname].nodes] }}

- name: list the nodes for '{{ inventory_hostname }}'
  debug:
    var: nodes

- name: process the nodes for '{{ inventory_hostname }}'
  include_tasks: node.yml
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node_name
