- name: get the group that lists this turing pi's nodes
  set_fact:
    this_bmc_nodes: "{{groups[inventory_hostname+'_nodes'] | list}}"

- name: debug
  debug:
    msg: |
      nodes in the current turingpi:
      {{ this_bmc_nodes }}

- name: process nodes
  include_tasks: node.yml
  loop: "{{ this_bmc_nodes }}"
  loop_control:
    loop_var: node_name
