# Tasks run against a single node in a turingpi

- name: fetch node variables for {{ node_name }}
  set_fact:
    node: "{{ hostvars[node_name] }}"

# determine if the node already exists
- name: wait for {{ node_name }} to respond on ssh port
  delegate_to: localhost
  wait_for:
    host: "{{ node_name }}"
    port: 22
    connect_timeout: 1
    timeout: 3
  register: node_status
  ignore_errors: true

- name: Flash images
  include_tasks: flash.yml
  # guard against flashing the image unless explicity requested
  when: reset | default(false) | bool or node.reset | default(false) | bool

- name: bootstrap node to enable further ansible provisioning
  include_tasks: bootstrap.yml
  when: reset | bool or node_status is failed
