# Tasks run against a single node in a turingpi

- name: fetch node variables for {{ node_name }}
  set_fact:
    node: "{{ hostvars[node_name] }}"
    do_reset_node: "{{ node.reset | default(false) | bool or do_reset }}"

# determine if the node already exists
- name: wait for {{ node_name }} to respond on ssh port
  delegate_to: localhost
  wait_for:
    host: "{{ node_name }}"
    port: 22
    timeout: 2
  register: node_status
  ignore_errors: true

- name: Flash images
  include_tasks: flash.yml
  # guard against flashing the image unless explicity requested
  when: do_reset_node or (do_flash and node_status is failed)

- name: bootstrap node to enable further ansible provisioning
  include_tasks: bootstrap.yml
  when: do_reset_node or node_status is failed
