# Tasks run against a single node in a turingpi

- name: fetch node variables
  set_fact:
    node: "{{ hostvars[node_name] }}"

- name: create temp folder
  delegate_to: localhost
  file:
    name: "{{ temp_folder }}"
    state: directory

# determine if the node already exists and has an anisble account
- name: wait for {{ node_name }}
  wait_for_connection:
    timeout: 1
  register: node_status
  ignore_errors: true

- name: Flash images
  include_tasks: flash.yml
  # guard against flashing the image unless explicity requested
  when: reset or (node_status is failed and flash_image)

- name: bootstrap node to enable further ansible provisioning
  include_tasks: bootstrap.yml
  loop: "{{ this_bmc_nodes }}"
  loop_control:
    loop_var: node
  when: reset or node_status is failed
