- name: Check dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Render the echo service and ingress manifests
  ansible.builtin.set_fact:
    echo_manifest: "{{ lookup('template', 'echo.yaml') }}"
    echo_ingress: "{{ lookup('template', 'ingress.yaml') }}"
  vars:
    namespace: default
    service_name: echo-service
    subdomain: echo

- name: Debug
  ansible.builtin.debug:
    var: manifest

- name: Remove echo service
  kubernetes.core.k8s:
    definition: |
      {{ echo_manifest }}
      ---
      {{ echo_ingress }}
    state: absent
  when: cluster_force
  failed_when: false

- name: Create a simple echo service
  kubernetes.core.k8s:
    definition: |
      {{ echo_manifest }}
      ---
      {{ echo_ingress }}
    namespace: default
  # echo requires ingress and certs to work
  when: ingress_controller_exists
