- name: Check dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Render the echo service definition
  ansible.builtin.template:
    src: echo.yaml
    dest: /tmp/echo.yaml
    mode: "0644"

- name: Create a simple echo service with tls ingress
  kubernetes.core.k8s:
    src: /tmp/echo.yaml
  # echo requires ingress and certs to work
  when: ingress_controller_exists and cert_manager_exists
