- name: Check dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Prepare values for ingress settings
  ansible.builtin.template:
    src: grafana_values.yaml
    dest: /tmp/grafana_values.yaml
    mode: "0644"
    vars:
      do_ingress: "{{ ingress_controller_exists }}"
  when: ingress_controller_exists

- name: Prepare ingress settings
  ansible.builtin.set_fact:
    # https://github.dev/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
    grafana_ingress_values:
when: ingress_controller_exists

- name: Install the helm chart for Grafana and Prometheus
  ansible.builtin.include_tasks:
    file: check_helm.yml
  vars:
    ch_release_name: grafana-prometheus
    ch_namespace: monitoring
    ch_chart_repo_url: https://prometheus-community.github.io/helm-charts/
    ch_chart_ref: kube-prometheus-stack
    ch_values: "{{ grafana_ingress_values | default({}) }}"

- name: Create port forward script for Grafana
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/grafana.sh"
    content: |
      #!/bin/bash

      # Start a port-forward to the Grafana and background it
      nohup kubectl -n monitoring port-forward deployment/grafana-prometheus 3000 &> /tmp/grafana-proxy.out &

      echo
      echo Grafana will be available at:
      echo   http://localhost:3000
    mode: "0755"
