- name: Install Grafana on the cluster
  kubernetes.core.helm:
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    chart_ref: kube-prometheus-stack
    release_name: grafana-prometheus
    create_namespace: true
    namespace: monitoring
    state: present
    values:
      persistence:
        enabled: true
        size: 10Gi
      adminPassword: "admin"

- name: Create port forward script for Grafana
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/grafana.sh"
    content: |
      #!/bin/bash

      # Start a port-forward to the Grafana and background it
      nohup kubectl -n monitoring port-forward deployment/grafana-prometheus 3000 &> /tmp/grafana-proxy.out &

      echo
      echo Grafana will be available at:
      echo   http://localhost:3000
    mode: '0755'
