- name: Install Grafana on the cluster
  kubernetes.core.helm:
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    chart_ref: kube-prometheus-stack
    release_name: grafana-prometheus
    create_namespace: true
    namespace: monitoring
    state: present
    # https://github.dev/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
    values:
      grafana:
        grafana.ini:
          server:
            domain: "{{ k3s_cluster_domain }}"
            root_url: https://{{ k3s_cluster_domain }}/grafana/
            serve_from_sub_path: true
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - "{{ k3s_cluster_domain }}"
          path: /grafana
        # adminPassword: "prom-operator"
        #
        # # To make Grafana persistent (Using Statefulset)
        # TODO - need a decent storage class to use this
        # persistence:
        #   enabled: true
        #   type: sts
        #   storageClassName: "storageClassName"
        #   accessModes:
        #     - ReadWriteOnce
        #   size: 20Gi
        #   finalizers:
        #     - kubernetes.io/pvc-protection
