# Occasionally ingress-nginx-nginx-admission-patch hangs and once this happens
# a reboot of all nodes is the only fix.

# use a retry block to reboot the nodes if the install fails
- name: Install Ingress with Retry Logic
  block:
    - name: Increment the retry count
      ansible.builtin.set_fact:
        retry_count: "{{ retry_count | default(0) | int + 1 }}"

    - name: Install the helm chart for cert-manager
      ansible.builtin.include_tasks:
        file: check_helm.yml
      vars:
        ch_release_name: nginx
        ch_namespace: ingress-nginx
        ch_chart_repo_url: https://kubernetes.github.io/ingress-nginx
        ch_chart_ref: ingress-nginx
        values:
          controller:
            service:
              loadBalancerIP: "{{ k3s_control_plane_ip }}"

  rescue:
    - name: Check for maximum retries
      ansible.builtin.fail:
        msg: Maximum retries of grouped tasks reached
      when: retry_count | int == 2

    # TODO this runs in series - how to parallelise?
    - name: Reboot all nodes
      ansible.builtin.reboot:
      become: true
      delegate_to: "{{ node }}"
      changed_when: true
      loop: "{{ groups['all_nodes'] }}"
      loop_control:
        loop_var: node

    - name: Recurse into self for a retry
      ansible.builtin.include_tasks: ingress.yml
