# Occasionally ingress-nginx-nginx-admission-patch fails and once this happens
# a reboot of the control plane node is the only fix.

# use a retry block to reboot the control plan if the install fails
- name: Install Ingress with Retry Logic
  block:
    - name: Increment the retry count
      ansible.builtin.set_fact:
        retry_count: "{{ retry_count | default(0) | int + 1 }}"

    - name: Install the helm chart for cert-manager
      ansible.builtin.include_tasks:
        file: check_helm.yml
      vars:
        ch_release_name: nginx
        ch_namespace: ingress-nginx
        ch_chart_repo_url: https://kubernetes.github.io/ingress-nginx
        ch_chart_ref: ingress-nginx
        ch_force: "{{ cluster_force }}"
        ch_values:
          controller:
            service:
              loadBalancerIP: "{{ k3s_control_plane_ip }}"
        ch_timeout: 40

    - name: Get status of job.batch/nginx-ingress-nginx-admission-patch
      kubernetes.core.k8s_info:
        kind: Job
        name: nginx-ingress-nginx-admission-patch
        namespace: ingress-nginx
      register: ingress_nginx_admission_patch
      failed_when: ingress_nginx_admission_patch.resources[0].status.failed | default(false)

  rescue:
    - name: Check for maximum retries
      ansible.builtin.fail:
        msg: Maximum retries of grouped tasks reached
      when: retry_count | int == 2

    - name: Reboot the node
      ansible.builtin.reboot:
      become: true
      delegate_to: "{{ k3s_control_plane }}"

    - name: Retry the ingress task
      ansible.builtin.include_tasks:
        file: ingress.yml
      vars:
        cluster_force: true
