- name: Install nginx-ingress on the cluster with IP {{ k3s_control_plane_ip }}
  kubernetes.core.helm:
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_ref: ingress-nginx
    release_name: nginx-ingress
    create_namespace: true
    namespace: nginx-ingress
    state: present
    values:
      controller:
        service:
          type: LoadBalancer
          loadBalancerIP: "{{ k3s_control_plane_ip }}"
