- name: Check dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Taint the control plane node to avoid it being used for longhorn storage
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ k3s_control_plane }}"
      spec:
        taints:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule

- name: Create a longhorn namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: longhorn-system

# These instructions for longhorn
# https://drunkcoding.net/posts/ks-07-hosting-longhorn-on-kubernetes/
# describe installing two manifests in order to get iscsi and nfsv4 drivers
# installed on the nodes.
# the add_remove.yml task file is used for these steps

# this manifest adds the open-iscsi driver to all nodes

- name: Set up iscsi driver
  ansible.builtin.include_tasks: add_remove.yml
  vars:
    ar_namespace: longhorn-system
    ar_manifest: "{{ cluster_longhorn_iscsi_manifest }}"
    ar_filter: iscsi
    ar_log_options: -c iscsi-installation
    ar_log_message: iscsi install successfully

- name: Set up nfs driver
  ansible.builtin.include_tasks: add_remove.yml
  vars:
    ar_namespace: longhorn-system
    ar_manifest: "{{ cluster_longhorn_nfs_manifest }}"
    ar_filter: nfs
    ar_log_options: -c nfs-installation
    ar_log_message: nfs install successfully
