# install services in the cluster

# Gather facts for the cluster master node
- name: Gather facts for control plane server
  ansible.builtin.setup:
    filter: "ansible_default_ipv4"
  delegate_to: "{{ k3s_control_plane }}"
  delegate_facts: true

# Install optional services from cluster_install_list
- name: Cluster Install of services
  ansible.builtin.include_tasks: "{{ cluster_service }}.yml"
  loop: "{{  cluster_install_list }}"
  when: cluster_install_list is defined
  loop_control:
    loop_var: cluster_service
