# install services in the cluster

# Gather facts for the cluster master node
- name: Gather facts for control plane server
  ansible.builtin.setup:
    filter: "ansible_default_ipv4"
  delegate_to: "{{ k3s_control_plane }}"
  delegate_facts: true

# Install optional services from install_list
- name: Cluster Install of {{ item }}
  ansible.builtin.include_tasks: "{{ item }}.yml"
  loop: "{{  install_list }}"
  when: install_list is defined
