# Gathering facts like this allows the role to be run standalone
- name: Gather facts for package manager
  ansible.builtin.setup:
    filter: ansible_pkg_mgr

# I can't use the generic package manager module because it does not
# have update_cache.
- name: Update all packages with apt
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    only_upgrade: true
  become: true
  register: update_result
  notify: Reboot the node
  when: ansible_pkg_mgr == 'apt'

- name: Update all packages with dnf
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
    update_only: true
  become: true
  register: update_result
  notify: Reboot the node
  when: ansible_pkg_mgr == 'dnf'

- name: Update all packages with pacman
  community.general.pacman:
    upgrade: true
  become: true
  register: update_result
  notify: Reboot the node
  when: ansible_pkg_mgr == 'pacman'
