# https://github.dev/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
grafana:
  adminPassword: {{ admin_password }}

{% if (ingress_controller_exists | bool) %}
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - grafana.{{ cluster_domain }}
    tls:
      - secretName: tls-cloudflare
        hosts:
          - grafana.{{ cluster_domain }}
    path: /
{% endif %}

{% if (longhorn_installed | bool) %}
  persistence:
    enabled: true
    type: sts
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
{% endif %}