apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ service_name }}-ingress"
  annotations:
    kubernetes.io/tls-acme: "true"
{% if service_port | default(80) == 443 %}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
{% endif %}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ host_url }}"
      secretName: "{{ service_name }}-secret"
  rules:
    - host: "{{ host_url }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ service_name }}
                port:
                  number: {{ service_port | default(80) }}
