# Description: This file contains the variables that are common to all the hosts in the inventory.

# The user to create on each node for access by ansible
ansible_account: "ansible"
# The user used to connect to the tpi BMCs
tpi_user: root
# A path to some storage on the tpi BMCs used for downloading os images
tpi_images_path: /mnt/sdcard/images
# default vault password file
vault_password_file: "~/.ansible_vault_password"

# pass '-e debug=true' to ansible-playbook to enable debug output
do_debug: "{{ debug | default(false) | bool }}"
# pass 'e reset=true' to reflash all nodes'
do_reset: "{{ reset | default(false) | bool }}"
# pass '-e flash=true' to flash nodes that are not responding to ssh
do_flash: "{{ flash | default(false) | bool }}"

local_tmp: "/tmp/iac2"
host_keys_vars: "vars/secrets/host_keys/keys.yml"
host_keys_folder: "{{ host_keys_vars | dirname }}"
