# Description: This file contains the variables that are common to all the hosts in the inventory.

# If reset is true, always flash ubuntu image onto all nodes
reset: False
# flash an image onto the nodes if they are not currently responding
flash_image: False

tpi_user: root
tpi_default_password: turing
# TODO replace this with vaulted pwd
tpi_password: "hello1234"
