# Description: This file contains the variables that are common to all the hosts in the inventory.

# If reset is true, always flash ubuntu image onto all nodes
# WARNING: this will overwrite the existing OS on the RK1 nodes
reset: False
# flash an image onto the nodes, only if they are no currently responding
flash_image: True

# To set up access to the BMC:
# - ssh root@turingpi with password turing
# - passws # change the password to something more secure
# - mkdir .ssh
# - echo 'xxxx' > .ssh/authorized_keys # where xxxx is your public ssh key
#
# Then invoke the ansible playbook with '-e reset=true tpi_password=xxxx'
# for initial setup of the turing pis
tpi_user: root
tpi_password: turing
