# Description: This file contains the variables that are common to all the hosts in the inventory.

# The user to create on each node for access by ansible
ansible_account: "ansible"
# The user used to connect to the tpi BMCs
tpi_user: root
# A path to some storage on the tpi BMCs used for downloading os images
tpi_images_path: /mnt/sdcard/images
# default vault password file
vault_password_file: "~/.ansible_vault_password"

# location of binaries we install in the execution environment
# the devcontainer sets 2 environment variables for these
bin_dir: "{{ lookup('ansible.builtin.env', 'BIN_DIR', default='${HOME}/bin') }}"
zshrc: "{{ lookup('ansible.builtin.env', 'ZSHRC', default='${HOME}/.zshrc') }}"

# tracks the node name of the control plane
k3s_control_plane_ip: "{{ hostvars[k3s_control_plane]['ansible_default_ipv4']['address'] }}"
# k3s_version is blank for latest stable release or use a specific version fr
# https://github.com/k3s-io/k3s/releases e.g. v1.29.11+k3s1
k3s_version:

# control which phases of the ALL playbook are run. Override on the command line
do_flash: false
do_k3s: true
do_cluster: true

################################################################################
# EDIT BELOW ###################################################################
# The remaining variables are for personalization of the cluster ###############
################################################################################

local_domain: .lan # how to address local nodes with dig
k3s_control_plane: node01 # the node name of the control plane
k3s_cluster_domain: node01.lan # the internal DNS name of the control plane node
k3s_cluster_external_domain: gilesk.ddns.net
domain_email: giles.knap@gilesk.ddns.net

# List of features to install into the cluster, comment out to remove.
# Each entry must match the name of a tasks yaml file in the cluster role.
cluster_install_list:
  - ingress
  - lets_encrypt
  - dashboard
  - grafana
  - echo
  - longhorn
