# details of the Ubuntu OS images to flash onto the nodes
flash_rp4_vers: "24.04.1"
flash_rk1_vers: "24.04"

flash_image_info:
  rk1:
    url: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-{{ flash_rk1_vers }}-preinstalled-server-arm64-turing-rk1.img.xz
    sha: 88584d5797bac01efd3bb1063935ce9f00947e4d4aa0c671d0a39ec8db6ca8f7
    os_file: "{{ flash_local_tmp }}/rk1.os.ubuntu-{{ flash_rk1_vers }}.img.xz"
    osf_remote: "{{ tpi_images_path }}/rk1.os.ubuntu-{{ flash_rk1_vers }}.img.xz"
  pi4:
    url: https://cdimage.ubuntu.com/releases/{{ flash_rp4_vers }}/release/ubuntu-{{ flash_rp4_vers }}-preinstalled-server-arm64+raspi.img.xz
    sha: e59925e211080b20f02e4504bb2c8336b122d0738668491986ee29a95610e5b1
    os_file: "{{ flash_local_tmp }}/os.raspi{{ flash_rp4_vers }}.img.xz"
    osf_remote: "{{ tpi_images_path }}/os.raspi{{ flash_rp4_vers }}.img.xz"

# force re-flash of nodes even if they are already contactable
flash_force: false

# a local temporary directory for flash images
flash_local_tmp: /tmp/iac2
# a debugging flag to skip the actual flash step
flash_pre_flashed: false
