# Install the control plane for k3s

- name: Remove k3s control plane if force is true
  ansible.builtin.command:
    cmd: k3s-uninstall.sh
    removes: /usr/local/bin/k3s-uninstall.sh
  when: k3s_force

- name: Install k3s control plane
  ansible.builtin.command:
    cmd: |-
      /tmp/k3s.sh server
      --disable=traefik
      --flannel-backend=host-gw
      --tls-san={{ k3s_control_plane_ip }}
      --bind-address={{ k3s_control_plane_ip }}
      --advertise-address={{ k3s_control_plane_ip }}
      --node-ip={{ k3s_control_plane_ip }}
      --cluster-init
    creates: /var/lib/rancher/k3s/server/node-token
  when: is_control_plane
  become: true
