- name: Read kubeconfig from /etc/rancher/k3s/k3s.yaml
  ansible.builtin.command:
    cmd: cat /etc/rancher/k3s/k3s.yaml
  delegate_to: "{{ k3s_control_plane }}"
  become: true
  register: kube_config
  changed_when: false
  run_once: true

- name: Write kubeconfig to $HOME/.kube/config
  ansible.builtin.copy:
    content: "{{ kube_config.stdout | regex_replace('127.0.0.1', k3s_control_plane_ip) }}"
    dest: "$HOME/.kube/config"
    mode: "0600"
  delegate_to: localhost
  run_once: true
