# example echo app for testing deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ealen/echo-server
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: default
spec:
  ports:
    - port: 80
  selector:
    app: echo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: default
  # ADD TLS #1
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  # ADD TLS #2
  tls:
    # Replace the domain below with your domain accordingly.
    - hosts:
        - echo.{{ k3s_cluster_external_domain }}
      secretName: tls-echo-cloudflare
  rules:
    # Replace the domain below with your domain accordingly.
    - host: echo.{{ k3s_cluster_external_domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: echo-service
                port:
                  number: 80
