apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ subdomain }}-ingress"
  namespace: "{{ namespace }}"
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ subdomain }}.{{ k3s_cluster_external_domain }}"
      secretName: tls-cloudflare
  rules:
    - host: "{{ subdomain }}.{{ k3s_cluster_external_domain }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: "{{ service_name }}"
                port:
                  number: 80
