# Gathering facts like this allows the role to be run standalone
- name: Gather facts for package manager
  ansible.builtin.setup:
    filter: ansible_pkg_mgr

- name: Update all packages with apt
  ansible.builtin.apt:
    name: "{{ tools_additional_packages | list }}"
    state: present
    update_cache: true
  become: true
  register: apt_result
  when: ansible_pkg_mgr == 'apt'

- name: Update all packages with dnf
  ansible.builtin.dnf:
    name: "{{ tools_additional_packages | list }}"
    state: present
    update_cache: true
  become: true
  register: dnf_result
  when: ansible_pkg_mgr == 'dnf'

- name: Update all packages with pacman
  community.general.pacman:
    name: "{{ tools_additional_packages | list }}"
    state: present
  become: true
  register: pacman_result
  when: ansible_pkg_mgr == 'pacman'
