- name: Get the requested root partition for the node
  ansible.builtin.set_fact:
    root_dev: "{{ hostvars[inventory_hostname].root_dev }}"
  when: hostvars[inventory_hostname].root_dev is defined

- name: Execute move of root partition for those nodes that need it
  ansible.builtin.include_tasks: move_fs.yml
  when: root_dev is defined
