# Set up the images on all the nodes in a given turing pi (1-4)

- name: get OS image
  get_url:
    url: "{{ image.url }}"
    dest: "{{ image.os_file }}"

- name: get OS sha file
  get_url:
    url: "{{ image.sha }}"
    dest: "{{ image.sha_file }}"

- name: set sha256
  set_fact:
    sha256: "{{ lookup('file', image.sha_file) | regex_search('([^ ]*)','\\1') | first }}"

- name: debug
  debug:
    msg: |-
      {{ sha256 }}

- name: flash-image
  command:
    cmd: |-
      tpi flash -n {{ hostvars[node].host_num }} --user root --password turing
      --host {{ hostvars[node].bmc }} --image-path {{ image.os_file }}
      --sha256 {{ sha256 }}
