- name: Gather facts for control plane server
  ansible.builtin.setup:
    filter: "ansible_default_ipv4"
  delegate_to: "{{ control_plane }}"
  delegate_facts: true

# Occasionally ingress-nginx-nginx-admission-patch job fails and once this happens
# a reboot of all nodes is the only fix. We now always reboot all the k3s nodes
# immediately after k3s is installed to avoid this issue (hopefully).

- name: Install the helm chart for nginx ingress
  kubernetes.core.helm:
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_ref: ingress-nginx
    release_name: nginx
    create_namespace: true
    force: "{{ cluster_force }}"
    namespace: ingress-nginx
    values:
      controller:
        service:
          loadBalancerIP: "{{ control_plane_ip }}"
  timeout: 40
  retries: 1
  delay: 10
