- name: Create the Keycloak namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: keycloak
    state: present

- name: Install Keycloak manifest
  kubernetes.core.k8s:
    namespace: keycloak
    state: present
    src: "{{ cluster_keycloak_manifest }}"

- name: Download Keycloak ingress
  ansible.builtin.get_url:
    url: "{{ cluster_keycloak_ingress }}"
    dest: /tmp/keycloak-ingress.yaml
    mode: "0644"

- name: Set the Keycloak host in the ingress
  ansible.builtin.replace:
    path: /tmp/keycloak-ingress.yaml
    regexp: KEYCLOAK_HOST
    replace: "{{ k3s_cluster_domain }}"
    mode: "0644"

- name: Install Keycloak ingress
  kubernetes.core.k8s:
    namespace: keycloak
    state: present
    src: /tmp/keycloak-ingress.yaml
