# main ansible execution environment
# TODO: create this with docker compose instead of running on a workstation
controller:
  hosts:
    localhost:
      ansible_connection: local

# this section lists the BMC for each turing pi
turing_pis:
  hosts:
    turingpi:
    # turingpi2:
  vars:
    ansible_user: "{{ tpi_user }}"

# this section lists the nodes, grouped by their turing pi
nodes:
  vars:
    ansible_user: ansible
  children:
    turingpi_nodes:
      # nodes for the first turing pi
      hosts:
        node01:
          slot_num: 1
          type: rk1
        node04:
          slot_num: 4
          type: pi4
          is_control_plane: true
    # example second turing pi
    # tp2:
    #   hosts:
    #     node05:
    #       slot_num: 1
