# main ansible execution environment
# This is typically the developer container that comes with this repo
controller:
  hosts:
    localhost:
      ansible_connection: local

# this section lists the BMC for each turing pi
turing_pis:
  hosts:
    turingpi:
  vars:
    ansible_user: "{{ tpi_user }}"
    nodes_group: tp1_nodes

# this section lists the nodes, grouped by their turing pi.
# types can be pi4 and rk1 at present
tp1_nodes:
  hosts:
    node01:
      slot_num: 1
      type: pi4
      is_control_plane: true
    node02:
      slot_num: 2
      type: rk1
    node03:
      slot_num: 3
      type: rk1
  vars:
    ansible_user: "{{ ansible_account }}"
    tp_name: turingpi
# example second turing pi
# tp2_nodes:
#   hosts:
#     node05:
#       slot_num: 1
#       type: rk1
#   vars:
#     ansible_user: ansible
#     tp_name: turingpi2
