controller:
  hosts:
    localhost:
turing_pis:
  children:
    tp1:
      hosts:
        node01:
          host_num: 1
          mac: aa:86:24:92:53:6e
          addr: 192.168.0.41
          is_control_plane: true
        node02:
          host_num: 2
          mac: aa:86:24:92:53:60
          addr: 192.168.0.42
      vars:
        bmc: turingpi
    # example second turing pi
    # tp2:
    #   hosts:
    #     node05:
    #       host_num: 1
    #       mac: aa:86:24:92:53:ee
    #       addr: 192.168.0.45
    #   vars:
    #     bmc: turingpi2
