# main ansible execution environment
# TODO: create this with docker compose instead of running on a workstation
controller:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"

# this section lists the BMC for each turing pi
turing_pis:
  hosts:
    turingpi:
    # turingpi2:
  vars:
    ansible_user: "{{ tpi_user }}"

# this section lists the nodes, grouped by their turing pi
nodes:
  children:
    turingpi_nodes:
      # nodes for the first turing pi
      hosts:
        node01:
          host_num: 1
          is_control_plane: true
        # node02:
        #   host_num: 2
    # example second turing pi
    # tp2:
    #   hosts:
    #     node05:
    #       host_num: 1
    #   vars:
    #     bmc: turingpi2
