# main ansible execution environment
# This is typically the developer container that comes with this repo
controller:
  hosts:
    localhost:
      ansible_connection: local

# this section lists the BMC for each turing pi
turing_pis:
  hosts:
    turingpi:
      nodes_group: tp1_nodes
  vars:
    ansible_user: "{{ tpi_user }}"

# this section lists the nodes, grouped by their turing pi.
# types can be pi4 and rk1 at present
tps:
  children:
    tp1_nodes:
      hosts:
        node01:
          slot_num: 1
          type: pi4
        node02:
          slot_num: 2
          type: rk1
        node03:
          slot_num: 3
          type: rk1
      vars:
        tp_name: turingpi
    # example second turing pi
    #  tp2_nodes:
    #    hosts:
    #      node05:
    #        slot_num: 1
    #        type: rk1
    #    vars:
    #      tp_name: turingpi2

  # variables shared by all nodes in all turing pi groups
  vars:
    control_plane: node01 # this is single control plan setup only
    ansible_user: "{{ ansible_account }}"
