# main ansible execution environment
# TODO: create this with docker compose instead of running on a workstation
controller:
  hosts:
    localhost:
      ansible_connection: local

# this section lists the BMC for each turing pi
turing_pis:
  hosts:
    turingpi:
  vars:
    ansible_user: "{{ tpi_user }}"
    nodes_group: tp1_nodes

# this section lists the nodes, grouped by their turing pi
tp1_nodes:
  hosts:
    node01:
      slot_num: 1
      type: rk1
    node04:
      slot_num: 4
      type: pi4
      is_control_plane: true
  vars:
    ansible_user: ansible
    tp_name: turingpi
# example second turing pi
# tp2_nodes:
#   hosts:
#     node05:
#       slot_num: 1
#       type: rk1
#   vars:
#     ansible_user: ansible
#     tp_name: turingpi2
