# main ansible execution environment
# The controller is typically the developer container that comes with this repo
controller:
  hosts:
    localhost:
      ansible_connection: local

# this section lists the BMC DNS name for each turing pi
turing_pis:
  hosts:
    turingpi:
  # turingpi2:
  vars:
    ansible_user: "{{ tpi_user }}"

# node names for nodes in turingpi
turingpi_nodes:
  hosts:
    node01:
      slot_num: 1
      type: pi4
    node02:
      slot_num: 2
      type: rk1
      root_dev: /dev/nvme0n1 # moves the root fs to the nvme drive
    node03:
      slot_num: 3
      type: rk1
  # example second turing pi
  #  turingpi2_nodes:
  #    hosts:
  #      node05:
  #        slot_num: 1
  #        type: rk1
  vars:
    ansible_user: "{{ ansible_account }}"

# Additional nodes that are not in a turing pi.
# OS pre-installed and pb_add_nodes.yml run to add them to ansible control.
extra_nodes:
  hosts:
    # nuc1:
    # nuc2:
  vars:
    ansible_user: "{{ ansible_account }}"

all_nodes:
  children:
    turingpi_nodes:
    # turinpi2_nodes:
    extra_nodes:
