---
- name: Get local facts
  hosts: localhost
  gather_facts: true
  roles:
    - role: setup

- name: Bare metal provisioning of turing_pi nodes
  hosts: turing_pis
  gather_facts: false
  roles:
    - role: flash

