---
- name: Get local facts
  hosts: localhost
  gather_facts: true
  roles:
    - role: setup

- name: Bare metal provisioning of turing_pi nodes
  hosts: turing_pis
  gather_facts: false
  vars_files:
    - "{{ host_keys_vars }}"

  roles:
    - role: ubuntu

- name: Prepare the nodes for further provisioning
  hosts: tp?_nodes # all nodes in all turing pi groups
  # only gather facts after the nodes have been set up by the ubuntu_rk1 role
  gather_facts: false
  roles:
    - role: known_hosts
    - role: k3s
