---
- name: Get local facts
  hosts: localhost
  gather_facts: true
  roles:
    - role: setup

- name: Bare metal provisioning of turing_pi nodes
  hosts: turing_pis
  gather_facts: false
  roles:
    - role: flash

- name: Prepare the nodes for further provisioning
  hosts: all_nodes
  # only gather facts after the nodes are added to known_hosts
  gather_facts: false
  roles:
    - role: known_hosts

- name: Move root partition to another device
  hosts: all_nodes
  roles:
    - role: move_fs
