---
- name: initial setup
  hosts: localhost
  gather_facts: true
  roles:
    - role: setup

- name: bare metal provisioning of turing_pi nodes
  hosts: turing_pis
  gather_facts: false
  vars_files:
    - "{{ host_keys_vars }}"
  roles:
    - role: ubuntu
