---
# TEST ONLY
# validate that we can read private host keys
- hosts: tp?_nodes
  gather_facts: false

  vars_files:
    - secrets/host_keys/keys.yml

  tasks:
    - name: read out the private key
      debug:
        var: "{{ inventory_hostname }}_pri"
    - name: read out the public key
      debug:
        var: "{{ inventory_hostname }}_pub"
