# A playbook to generate the secrets folder and set initial passwords
#
# This is to be run on new forks of this repo for new infrastructure:
# Run once to set up credentials, then commit the changes to your fork.
# - fork this repo
# - edit hosts.yml to describe your infrastructure
# - delete the existing vars/secrets folder
# - remove all existing files in pub_keys
# - copy your public ssh key(s) into pub_keys
# - run this playbook to generate host keys for your nodes
---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Check secrets folder
      stat:
        path: "{{ playbook_dir }}/vars/secrets"
      register: secrets_dir

    - name: Error if exists
      assert:
        that: not secrets_dir.stat.exists
        msg: "vars/secrets folder already exists, please remove it before running this playbook"

    - name: check for master public key
      stat:
        path: "{{ playbook_dir }}/pub_keys/ansible_rsa.pub"
      register: master_key

    - name: create secrets folder
      file:
        path: directory_data.stat.path
        state: directory

# Validate the BMC password has been set correctly
- hosts: turing_pis
  gather_facts: false

  tasks:
    - name: Check turing pi BMC has ssh keys
      raw: echo test

- hosts: tp?_nodes
  gather_facts: false

  tasks:
    - name: Print a message
      delegate_to: localhost
      debug:
        msg: "generate ssh keys for {{ inventory_hostname }}"
# -rw------- 1 root root    399 Oct 11 04:42 ssh_host_ed25519_key
# -rw-r--r-- 1 root root     93 Oct 11 04:42 ssh_host_ed25519_key.pub
