- name: Install Kubernetes on all nodes
  hosts: tp?_nodes # all nodes in all turing pi groups
  roles:
    - role: k3s

- name: Install client tools in execution environment
  hosts: localhost
  roles:
    - role: tools

- name: Remaining cluster setup via client tools in the execution environment
  hosts: localhost
  roles:
    - role: cluster
