- name: Install Kubernetes on all nodes
  hosts: all_nodes # all nodes in all turing pi groups
  roles:
    - role: k3s

- name: Install client tools in execution environment
  hosts: localhost
  roles:
    - role: tools
