---
- name: bare metal provisioning of turing_pi nodes
  hosts: turing_pis
  gather_facts: false
  roles:
    - role: ubuntu

- name: Set up kubernetes cluster
  hosts: nodes
  # only gather facts after the nodes have been set up by the ubuntu_rk1 role
  gather_facts: false
  roles:
    - role: known_hosts
    - role: k3s
