# Update each hosts ssh keys in known_hosts file.

- name: Remove all old hosts keys prior to adding them
  ansible.builtin.known_hosts:
    name: "{{ item }}"
    state: absent
  loop: "{{ groups['all_nodes'] }}"
  delegate_to: localhost
  run_once: true

- name: Get ssh public keys of new node {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.command:
    cmd: "ssh-keyscan {{ inventory_hostname }}"
  register: new_node_ssh_keys
  changed_when: false

- name: Add/update the host public key in {{ known_hosts_file }}
  delegate_to: localhost
  ansible.builtin.known_hosts:
    name: "{{ inventory_hostname }}"
    key: "{{ item }}"
    path: "{{ known_hosts_file }}"
    state: present
  loop: "{{ new_node_ssh_keys.stdout_lines }}"
  register: known_hosts_update
