# Update each hosts ssh keys in known_hosts file.

# Known hosts changes are unreliable when ip address entries are left in
# because they don't get replaced. This is particularly a problem when
# nodes are being rebuilt and we have not fixed an IP for each node name.
- name: Remove all ip address entries from known_hosts
  ansible.builtin.lineinfile:
    path: "{{ known_hosts_file }}"
    regexp: '^\|1\|.*'
    state: absent
  delegate_to: localhost
  changed_when: false # not always true, but it's benign
  run_once: true

# IMPORTANT: the playbook that runs this must use serial: 1
# to avoid race conditions with writing to the known_hosts file.
- name: Get ssh public keys of new node {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.command:
    cmd: "ssh-keyscan {{ inventory_hostname }}"
  register: new_node_ssh_keys
  changed_when: false

- name: Add/update the host public key in {{ known_hosts_file }}
  delegate_to: localhost
  ansible.builtin.known_hosts:
    name: "{{ inventory_hostname }}"
    key: "{{ item }}"
    path: "{{ known_hosts_file }}"
    state: present
  loop: "{{ new_node_ssh_keys.stdout_lines }}"
  when: not item.startswith('#')
  register: known_hosts_update
