# Update each hosts ssh keys in known_hosts file.

# IMPORTANT: the playbook that runs this must use serial: 1
# to avoid race conditions with writing to the local known_hosts file.

# First, remove any ip address known_hosts entries for the node.
- name: Remove old known_host IP entries for {{ inventory_hostname }}
  ansible.builtin.include_tasks:
    file: remove_ip.yml

# Second, remove any hostname known_hosts entries for the node
- name: Get ssh public keys of node {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.command:
    cmd: "ssh-keyscan {{ inventory_hostname }}"
  register: new_node_ssh_keys
  changed_when: false

- name: Add/update the host's public keys in known_hosts file
  delegate_to: localhost
  ansible.builtin.known_hosts:
    name: "{{ inventory_hostname }}"
    key: "{{ item }}"
    state: present
  loop: "{{ new_node_ssh_keys.stdout_lines }}"
  when: not item.startswith('#')
  register: known_hosts_update
