# Nodes will just have been created by the flash role, wait for them to be ready
# and update our known_hosts file with their ssh public keys

# wait until the node is ready to accept ssh connections
- name: Wait for {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
  register: node_status
  retries: 20
  delay: 6

- name: Get ssh public key of new node {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.command:
    cmd: "ssh-keyscan {{ inventory_hostname }}"
    creates: "/tmp/{{ inventory_hostname }}_ssh_key"
  register: new_node_ssh_keys
  changed_when: false

- name: Add/update the host public key in {{ known_hosts_file }}
  delegate_to: localhost
  ansible.builtin.known_hosts:
    name: "{{ inventory_hostname }}"
    key: "{{ item }}"
    path: "{{ known_hosts_file }}"
  loop: "{{ new_node_ssh_keys.stdout_lines }}"

- name: Debug message for node readiness
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} is ready"

- name: Gather facts on node {{ inventory_hostname }}
  ansible.builtin.setup:
