# reboot a host but remove its IP from known_hosts file first

# Remove any ip address known_hosts entries, in case the ip changes.
- name: Remove old known_host IP entries for {{ inventory_hostname }}
  ansible.builtin.include_tasks:
    file: remove_ip.yml

- name: Reboot {{ inventory_hostname }}
  ansible.builtin.reboot: # noqa no-handler
    reboot_timeout: 200
  become: true
  failed_when: false # fails to reconnect if the ip has changed
  register: reboot_result
