# version of longhorn to install
cluster_longhorn_version: v1.7.2
cluster_longhorn_cli_tool: "\
  https://github.com/longhorn/cli/releases/download/\
  {{ cluster_longhorn_version }}\
  /longhornctl-linux-amd64"

# uninstall and reinstall the cluster services if true
cluster_force: false
